name: RedWolf Recovery Builder

on:
  workflow_dispatch:
    inputs:
      DEVICE_TREE_URL:
        description: 'Device Tree URL (e.g., https://github.com)'
        required: true
        default: 'https://github.com/nehuk23/1'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'android-12.1'
      DEVICE_VENDOR:
        description: 'Device Vendor (e.g., xiaomi)'
        required: true
        default: 'samsung'
      DEVICE_NAME:
        description: 'Device Codename (e.g., mido)'
        required: true
        default: 'm14x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Build Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt clean

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc build-essential zip curl libstdc++6 git wget python3 gcc clang libssl-dev repo rsync
          git config --global user.name "BuildBot"
          git config --global user.email "bot@example.com"

      - name: Sync RedWolf Source
        run: |
          mkdir ~/redwolf && cd ~/redwolf
          repo init -u https://github.com -b 6.0
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Clone Device Tree
        run: |
          cd ~/redwolf
          git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} device/${{ github.event.inputs.DEVICE_VENDOR }}/${{ github.event.inputs.DEVICE_NAME }}

      - name: Build RedWolf
        run: |
          cd ~/redwolf
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload Recovery Image
        uses: actions/upload-artifact@v4
        with:
          name: RedWolf-${{ github.event.inputs.DEVICE_NAME }}
          path: ~/redwolf/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img
